import { z } from 'zod';
export const verticals=['gaming','consumer_platforms','retail_ecommerce','consumer_technology'] as const;
export const pairs=['JP:ja','KR:ko','BR:pt','LATAM:es','US:en'];
export const eventCategories=['product_launch_or_update','gaming_or_platform_outage','monetization_or_pricing','promotions_or_discounting','product_availability_or_stockout','refund_return_quality_or_defect','player_or_user_engagement','competitor_substitution','store_channel_or_distribution','regulatory_or_reputation','merchant_creator_or_partner_issue'] as const;
const market=z.object({market_code:z.string(),language_code:z.string(),company_aliases:z.array(z.string()),products_games_apps_brands:z.array(z.string()),competitor_aliases:z.array(z.string()),event_terms:z.record(z.array(z.string())),source_preferences:z.array(z.string()),ambiguity_notes:z.array(z.string()),enabled:z.boolean()});
export const companyProfile=z.object({ticker:z.string().trim().min(1),company_name_en:z.string().trim().min(1),exchange:z.string().trim().min(1),vertical:z.enum(verticals),cik:z.string().optional().default(''),description:z.string().optional().default(''),is_active:z.boolean(),priority_tier:z.number().int().min(1).max(3),markets:z.array(market).min(1)});
export type CompanyProfile=z.infer<typeof companyProfile>;
export function normalizeAlias(alias:string){return alias.normalize('NFKC').trim().toLocaleLowerCase().replace(/\s+/g,' ')}
export function profileWarnings(p:CompanyProfile){const warnings:string[]=[]; for(const m of p.markets.filter(x=>x.enabled)){const aliases=m.company_aliases.map(normalizeAlias); if(!aliases.length) warnings.push(`${m.market_code}/${m.language_code}: add at least one company alias`); if(aliases.some(a=>a.length<3)) warnings.push(`${m.market_code}/${m.language_code}: alias is very short`); if(new Set(aliases).size!==aliases.length) warnings.push(`${m.market_code}/${m.language_code}: duplicate aliases`); if(!m.event_terms||!Object.values(m.event_terms).some(v=>v.length)||!m.products_games_apps_brands.length) warnings.push(`${m.market_code}/${m.language_code}: add event terms or product terms`); if(!pairs.includes(`${m.market_code}:${m.language_code}`)) warnings.push(`unsupported market/language pair: ${m.market_code}/${m.language_code}`)} return warnings}
export function completeness(p:CompanyProfile){const checks=[!!p.ticker,!!p.company_name_en,!!p.exchange,!!p.vertical,p.markets.length>0,...p.markets.filter(m=>m.enabled).flatMap(m=>[m.company_aliases.length>0,m.products_games_apps_brands.length>0||Object.values(m.event_terms).some(v=>v.length)])]; return Math.round(checks.filter(Boolean).length/checks.length*100)}
export function researchPriority(input:{recency:number;sourceQuality:number;concentration:number;englishGap:number;penalty:number}){return Math.max(0,Math.min(100,Math.round(.35*input.recency+.30*input.sourceQuality+.20*input.concentration+.15*input.englishGap-input.penalty)))}
