import { z } from 'zod';
export const verticals=['gaming','consumer_platforms','retail_ecommerce','consumer_technology','semiconductors','memory_and_ai_hardware','battery_and_ev_supply_chain','automotive','industrial_defense','shipbuilding','etf','macro','other'] as const;
export const pairs=['JP:ja','KR:ko','BR:pt','LATAM:es','US:en'];
export const eventCategories=['earnings','guidance','supply_chain','regulation','product','management','legal','retail_flow','macro','capital_allocation','corporate_action','customer_demand'] as const;
const market=z.object({market_code:z.string(),language_code:z.string(),company_aliases:z.array(z.string()),negative_aliases:z.array(z.string()).default([]),products_games_apps_brands:z.array(z.string()),competitor_aliases:z.array(z.string()),event_terms:z.record(z.array(z.string())),source_preferences:z.array(z.string()),ambiguity_notes:z.array(z.string()),enabled:z.boolean()});
const relatedEntity=z.object({ticker:z.string().trim().min(1),relationship_type:z.string().trim().min(1),evidence_note:z.string().optional().default('')});
export const companyProfile=z.object({ticker:z.string().trim().min(1),company_name_en:z.string().trim().min(1),name_ko:z.string().optional().default(''),krx_code:z.string().optional().default(''),aliases_en:z.array(z.string()).default([]),aliases_ko:z.array(z.string()).default([]),topics_of_interest:z.array(z.string()).default([]),related_entities:z.array(relatedEntity).default([]),exchange:z.string().trim().min(1),vertical:z.enum(verticals),cik:z.string().optional().default(''),description:z.string().optional().default(''),is_active:z.boolean(),priority_tier:z.number().int().min(1).max(3),markets:z.array(market).min(1)});
export type CompanyProfile=z.infer<typeof companyProfile>;
export function normalizeAlias(alias:string){return alias.normalize('NFKC').trim().toLocaleLowerCase().replace(/\s+/g,' ')}
export function profileWarnings(p:CompanyProfile){const warnings:string[]=[];if(p.markets.some(m=>m.enabled&&m.market_code==='KR')&&!p.name_ko.trim())warnings.push('KR entity profile: add the reviewed Korean legal/common name');for(const m of p.markets.filter(x=>x.enabled)){const aliases=m.company_aliases.map(normalizeAlias);const negatives=m.negative_aliases.map(normalizeAlias); if(!aliases.length) warnings.push(`${m.market_code}/${m.language_code}: add at least one company alias`); if(aliases.some(a=>a.length<3)) warnings.push(`${m.market_code}/${m.language_code}: alias is very short`); if(new Set(aliases).size!==aliases.length) warnings.push(`${m.market_code}/${m.language_code}: duplicate aliases`); if(negatives.some(a=>aliases.includes(a)))warnings.push(`${m.market_code}/${m.language_code}: positive alias also appears in negative aliases`); if(!m.event_terms||!Object.values(m.event_terms).some(v=>v.length)||!m.products_games_apps_brands.length) warnings.push(`${m.market_code}/${m.language_code}: add event terms or product terms`); if(!pairs.includes(`${m.market_code}:${m.language_code}`)) warnings.push(`unsupported market/language pair: ${m.market_code}/${m.language_code}`)} return warnings}
export function completeness(p:CompanyProfile){const checks=[!!p.ticker,!!p.company_name_en,!!p.exchange,!!p.vertical,p.markets.length>0,...p.markets.filter(m=>m.enabled).flatMap(m=>[m.company_aliases.length>0,m.products_games_apps_brands.length>0||Object.values(m.event_terms).some(v=>v.length),m.market_code!=='KR'||!!p.name_ko])]; return Math.round(checks.filter(Boolean).length/checks.length*100)}
export function researchPriority(input:{recency:number;sourceQuality:number;concentration:number;englishGap:number;penalty:number}){return Math.max(0,Math.min(100,Math.round(.35*input.recency+.30*input.sourceQuality+.20*input.concentration+.15*input.englishGap-input.penalty)))}
