export type PreviewDocument={id:string;market:'KR'|'US';language:string;sourceType:'forum'|'news';sourceName:string;title:string;excerpt:string;publishedAt:string;topic:string;stance:'concern'|'neutral'|'watch';};
export const syntheticPreviewDocuments:PreviewDocument[]=[
 {id:'preview-kr-1',market:'KR',language:'ko',sourceType:'forum',sourceName:'Synthetic Korean forum sample',title:'[개발용 샘플] 플랫폼 수수료와 사용자 경험 논의',excerpt:'개발용 합성 문서입니다. 실제 포럼 게시물이나 뉴스가 아닙니다.',publishedAt:'2026-09-13T15:00:00Z',topic:'monetization_or_pricing',stance:'concern'},
 {id:'preview-kr-2',market:'KR',language:'ko',sourceType:'news',sourceName:'Synthetic Korean news sample',title:'[개발용 샘플] 서비스 업데이트 이후 이용자 반응',excerpt:'개발용 합성 문서입니다. 실제 보도나 이용자 의견이 아닙니다.',publishedAt:'2026-09-13T12:00:00Z',topic:'product_launch_or_update',stance:'neutral'},
 {id:'preview-kr-3',market:'KR',language:'ko',sourceType:'forum',sourceName:'Synthetic Korean forum sample',title:'[개발용 샘플] 환불 정책 변경에 대한 토론',excerpt:'개발용 합성 문서입니다. 실제 포럼 게시물이나 뉴스가 아닙니다.',publishedAt:'2026-09-12T21:00:00Z',topic:'refund_return_quality_or_defect',stance:'concern'},
 {id:'preview-us-1',market:'US',language:'en',sourceType:'news',sourceName:'Synthetic U.S. news sample',title:'[DEV SAMPLE] Product update coverage',excerpt:'Synthetic development document. This is not real news or a real market source.',publishedAt:'2026-09-13T14:00:00Z',topic:'product_launch_or_update',stance:'neutral'},
 {id:'preview-us-2',market:'US',language:'en',sourceType:'forum',sourceName:'Synthetic U.S. forum sample',title:'[DEV SAMPLE] Discussion of platform growth',excerpt:'Synthetic development document. This is not a real forum post or investor opinion.',publishedAt:'2026-09-12T18:00:00Z',topic:'player_or_user_engagement',stance:'neutral'}
];
export const syntheticPreviewTopics=['monetization_or_pricing','product_launch_or_update','refund_return_quality_or_defect','player_or_user_engagement'];
export function syntheticTopicRows(){return syntheticPreviewTopics.map(topic=>{const kr=syntheticPreviewDocuments.filter(d=>d.market==='KR'&&d.topic===topic).length;const us=syntheticPreviewDocuments.filter(d=>d.market==='US'&&d.topic===topic).length;const krTotal=syntheticPreviewDocuments.filter(d=>d.market==='KR').length;const usTotal=syntheticPreviewDocuments.filter(d=>d.market==='US').length;return {topic,krShare:kr/krTotal,usShare:us/usTotal,gap:kr/krTotal-us/usTotal,krCount:kr,usCount:us}})}
