import fs from 'node:fs';
import path from 'node:path';
import {parse as parseCsv} from 'csv-parse/sync';
import YAML from 'yaml';
import {createClient} from '@supabase/supabase-js';
import {validateProfile} from './validate_company_profiles';
function readProfiles(file:string):unknown[]{const text=fs.readFileSync(file,'utf8');const ext=path.extname(file).toLowerCase();if(ext==='.yaml'||ext==='.yml'){const value=YAML.parse(text);return Array.isArray(value)?value:[value]}if(ext==='.json'){const value=JSON.parse(text);return Array.isArray(value)?value:[value]}if(ext==='.csv'){return parseCsv(text,{columns:true,skip_empty_lines:true,relax_column_count:true}).map((row:Record<string,string>)=>({...row,is_active:row.is_active!=='false',priority_tier:Number(row.priority_tier||3),markets:[{market_code:row.market_code,language_code:row.language_code,company_aliases:split(row.company_aliases),products_games_apps_brands:split(row.products_games_apps_brands),competitor_aliases:split(row.competitor_aliases),event_terms:parseJson(row.event_terms,{}),source_preferences:split(row.source_preferences),ambiguity_notes:split(row.ambiguity_notes),enabled:row.enabled!=='false'}]}))}throw new Error(`Unsupported profile format: ${ext}`)}
function split(value?:string){return value?value.split('|').map(v=>v.trim()).filter(Boolean):[]} function parseJson(value:string|undefined,fallback:unknown){try{return value?JSON.parse(value):fallback}catch{return fallback}}
async function main(){const file=process.argv[2];if(!file){console.error('Usage: npm run import-profiles -- path/to/profiles.yaml [--apply]');process.exit(1)}const profiles=readProfiles(file);const reports=profiles.map(validateProfile);console.log(JSON.stringify({file,profiles:reports.length,reports},null,2));if(reports.some(r=>!r.valid)||!process.argv.includes('--apply')){if(!process.argv.includes('--apply'))console.log('Dry run only. Add --apply after fixing validation errors to upsert.');process.exit(reports.some(r=>!r.valid)?1:0)}const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for --apply');const db=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});for(let index=0;index<profiles.length;index++){const profile=profiles[index] as any;const {data:company,error}=await db.from('companies').upsert({ticker:profile.ticker,cik:profile.cik||null,company_name_en:profile.company_name_en,vertical:profile.vertical,exchange:profile.exchange,description:profile.description||null,priority_tier:profile.priority_tier,profile_completeness_score:reports[index].score,is_active:profile.is_active},{onConflict:'ticker'}).select('id').single();if(error)throw error;await db.from('company_market_profiles').delete().eq('company_id',company.id);const {error:marketError}=await db.from('company_market_profiles').insert(profile.markets.map((m:any)=>({company_id:company.id,market_code:m.market_code,language_code:m.language_code,company_aliases_json:m.company_aliases,products_games_apps_brands_json:m.products_games_apps_brands,competitor_aliases_json:m.competitor_aliases,event_terms_json:m.event_terms,ambiguity_notes:m.ambiguity_notes,source_preferences_json:m.source_preferences,enabled:m.enabled})));if(marketError)throw marketError}console.log('Applied validated profiles. Historical source records were preserved.')}main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exit(1)})
