import {NextRequest,NextResponse} from 'next/server';
import {serverSupabase} from '../../../lib/server-supabase';
import {GDELTConnector} from '../../../lib/connectors/gdelt';
import {RSSConnector} from '../../../lib/connectors/rss';
import {SECEdgarConnector} from '../../../lib/connectors/sec';
import type {NormalizedDocument} from '../../../lib/connectors/types';
export const runtime='nodejs';
export async function POST(request:NextRequest){if(request.headers.get('x-cron-secret')!==process.env.CRON_INTERNAL_SECRET)return NextResponse.json({error:'Unauthorized'},{status:401});const db=serverSupabase();if(!db)return NextResponse.json({error:'Supabase server configuration is missing'},{status:503});const start=new Date(Date.now()-72*60*60*1000),end=new Date();const {data:companies,error:companyError}=await db.from('companies').select('id,ticker,cik,is_active').eq('is_active',true);if(companyError)return NextResponse.json({error:companyError.message},{status:500});const rssFeeds=parseJson(process.env.RSS_FEEDS_JSON||'[]');const connectors=[] as Array<GDELTConnector|RSSConnector|SECEdgarConnector>;if(process.env.GDELT_ENABLED==='true')connectors.push(new GDELTConnector());if(process.env.RSS_ENABLED==='true'&&rssFeeds.length)connectors.push(new RSSConnector(rssFeeds));if(process.env.SEC_USER_AGENT)connectors.push(new SECEdgarConnector());const summary={companies:companies?.length??0,documentsStored:0,runs:0,errors:[] as string[]};for(const company of companies??[]){const {data:markets}=await db.from('company_market_profiles').select('*').eq('company_id',company.id).eq('enabled',true);for(const market of markets??[]){const aliases=[...(market.company_aliases_json??[]),...(market.products_games_apps_brands_json??[])].filter(Boolean).slice(0,12);const query=aliases.join(' OR ');for(const connector of connectors){const started=new Date();try{let result;if(connector instanceof SECEdgarConnector&&company.cik)result=await connector.fetchCompanyFilings(company.cik,company.id,start,end);else if(connector instanceof SECEdgarConnector)continue;else result=await connector.fetchDocuments({query,start,end,marketCode:market.market_code,languageCode:market.language_code,companyId:company.id});const docs=deduplicate(result.documents);if(docs.length){const {error}=await db.from('source_documents').upsert(docs.map(toRow),{onConflict:'content_hash'});if(error)throw error;summary.documentsStored+=docs.length}await db.from('connector_runs').insert({connector_name:connector.name,job_name:'manual-ingest',company_id:company.id,market_code:market.market_code,status:'completed',started_at:started.toISOString(),completed_at:new Date().toISOString(),items_fetched:result.documents.length,items_deduplicated:result.documents.length-docs.length,items_stored:docs.length,api_requests_used:result.requestsUsed,metadata_json:result.metadata})}catch(error){const message=error instanceof Error?error.message:String(error);summary.errors.push(`${connector.name}/${company.ticker}: ${message}`);await db.from('connector_runs').insert({connector_name:connector.name,job_name:'manual-ingest',company_id:company.id,market_code:market.market_code,status:'failed',started_at:started.toISOString(),completed_at:new Date().toISOString(),error_message:message})}summary.runs++}}}return NextResponse.json(summary)}
function parseJson(v:string):string[]{try{const parsed=JSON.parse(v);return Array.isArray(parsed)?parsed.filter(x=>typeof x==='string'):[]}catch{return []}}
function deduplicate(docs:NormalizedDocument[]){const seen=new Set<string>();return docs.filter(d=>{if(seen.has(d.contentHash))return false;seen.add(d.contentHash);return true})}
function toRow(d:NormalizedDocument){return {company_id:d.companyId,market_code:d.marketCode,source_type:d.sourceType,source_name:d.sourceName,source_domain:d.sourceDomain,language_code:d.languageCode,country_code:d.countryCode,title_original:d.titleOriginal,excerpt_original:d.excerptOriginal,source_url:d.sourceUrl,canonical_url:d.canonicalUrl,published_at:d.publishedAt,source_quality_tier:d.sourceQualityTier,entity_match_confidence:d.entityMatchConfidence,content_hash:d.contentHash,raw_metadata_json:d.rawMetadata}}
